meta_product_name: "Lengua Viva"
meta_title: "Lengua Viva - Level Up Your Language"
meta_description: "Practise foreign languages with authentic materials. Lengua Viva gives you personalised recommendations for songs, podcasts, articles and videos in your language of choice."
meta_image: "cover.png"
twitter_account: "@product_twitter_account"   # required for Twitter Cards
